In [15]:
#Задание 1

# загрузка функции-таймера
from timeit import default_timer as timer
# подключение библиотеки numpy
import numpy as np
N=int(input()) # размер одномерных массивов

# создание массива, равнораспределённого в диапазоне от 0 до 100
a1 = np.arange(0, 100, 100/N, dtype=float)
print('a1= ', a1)

# создание массива, равнораспределённого в интервале от 0 до 1
a2 = np.linspace(0, 1, N, dtype=float)
print('a2= ',a2)

# массив для сохранения результата сложения
result = np.zeros(N)

# сложение созданных массивов напрямую в цикле
start = timer() # запуск таймера
for i in range(N):
    result[i] = a1[i] + a2[i]
end = timer() # остановка таймера
print('a1+a2= ', result)
print('a) сложение массивов напрямую в цикле:')
print(u' время выполнения: %.3e с' % (end - start))

# быстрое сложение
print('б) сложение с помощью numpy:')
start = timer() # запуск таймера
result = a1 + a2
end = timer() # остановка таймера
print(' время выполнения: %.3e с' % (end - start))

10
a1=  [ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
a2=  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
a1+a2=  [ 0.         10.11111111 20.22222222 30.33333333 40.44444444 50.55555556
 60.66666667 70.77777778 80.88888889 91.        ]
a) сложение массивов напрямую в цикле:
 время выполнения: 3.917e-04 с
б) сложение с помощью numpy:
 время выполнения: 2.299e-04 с


In [33]:
#Задание 2

k1=int(input('Введите количество столбцов в матрице m1 '))
# создание матрицы m1
m1=np.transpose(np.array([a1]*k1))
print(m1)

k2=int(input('Введите количество строк в матрице m2 '))
# создание матрицы m2
m2=np.array([a2]*k2)
print(m2)

# умножение матриц напрямую в цикле
start = timer() # запуск таймера
result=[[0]*k1 for _ in range(k2)]
for i in range(k2):
    for j in range(k1):
        result[i][j]=0
        for l in range(N):
            result[i][j]+=m2[i][l]*m1[l][j]
end = timer() # остановка таймера
print(result)
print('a) умножение матриц напрямую в цикле:')
print(u' время выполнения: %.3e с' % (end - start)) 

# быстрое умножение матриц
start = timer() # запуск таймера
result=np.dot(m2, m1)
end = timer() # остановка таймера
print(result)
print('б) умножение матриц с помощью numpy:')
print(' время выполнения: %.3e с' % (end - start))

Введите количество столбцов в матрице m1 5
[[ 0.  0.  0.  0.  0.]
 [10. 10. 10. 10. 10.]
 [20. 20. 20. 20. 20.]
 [30. 30. 30. 30. 30.]
 [40. 40. 40. 40. 40.]
 [50. 50. 50. 50. 50.]
 [60. 60. 60. 60. 60.]
 [70. 70. 70. 70. 70.]
 [80. 80. 80. 80. 80.]
 [90. 90. 90. 90. 90.]]
Введите количество строк в матрице m2 3
[[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
  0.66666667 0.77777778 0.88888889 1.        ]
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
  0.66666667 0.77777778 0.88888889 1.        ]
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
  0.66666667 0.77777778 0.88888889 1.        ]]
[[316.66666666666663, 316.66666666666663, 316.66666666666663, 316.66666666666663, 316.66666666666663], [316.66666666666663, 316.66666666666663, 316.66666666666663, 316.66666666666663, 316.66666666666663], [316.66666666666663, 316.66666666666663, 316.66666666666663, 316.66666666666663, 316.66666666666663]]
a) умножение матриц напрямую в ци