In [2]:
import numpy as np

In [3]:
#доступ к элементам одномерного массива
a1 = np.array([1, 4, 5, 8])
print(a1[3], a1[0])

8 1


In [4]:
#доступ к элементам двумерного массива
a2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(a2[0, 1])

2.0


In [10]:
#срезы в одномерных массивах
a3 = np.linspace(0, 2, 9) 
print(a3)
print(a3[1:5:1])                   #вывод среза массива с 1-го элемента по 4-ый с шагом 1
print(a3[1:3])                     #вывод среза массива с 1-го элемента по 2-ой
print(a3[::])                      #вывод всего массива
print(a3[:])                       #вывод всего массива
print(a3[::2])                     #вывод каждого второго элемента массива
print(a3[4:])                      #вывод  массива начиная с 4-го элемента и до конца
print(a3[-3::])                    #вывод массива начиная с (9-3) = 6-го элемента и до конца
print(a3[:-3:])                    #вывод массива начиная с начала и заканчивая (9-3) = 6-ым элементом (не включительно)
print(a3[::-1])                    #вывод массива в обратном порядке

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.25 0.5  0.75 1.  ]
[0.25 0.5 ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.  0.5 1.  1.5 2. ]
[1.   1.25 1.5  1.75 2.  ]
[1.5  1.75 2.  ]
[0.   0.25 0.5  0.75 1.   1.25]
[2.   1.75 1.5  1.25 1.   0.75 0.5  0.25 0.  ]


In [11]:
#срезы в двумерных массивах
a4 = np.array([[-1, 0, 2, 4], [10, 20, 40, 80], [7, 7, 7, 7]])
print(a4)
print(a4[:, 0])                         #вывод нулевого столбца массива
print(a4[:, 1])                         #вывод первого столбца массива
print(a4[1, :])                         #вывод первой строки массива
print(a4[2, :])                         #вывод второй строки массива

[[-1  0  2  4]
 [10 20 40 80]
 [ 7  7  7  7]]
[-1 10  7]
[ 0 20  7]
[10 20 40 80]
[7 7 7 7]


In [12]:
#создаем одномерный массив из суммы 1-ой и 2-ой строк масива a4
new_array = a4[1, :] + a4[2, :]
print(new_array)

[17 27 47 87]
