In [1]:
import numpy as np

In [3]:
#Универсальные функции
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
print(a + b)            #поэлементное сложение массивов
print(a-b)              #поэлементная разность массивов
print(a * b)            #поэлементное перемножение массивов
print(b / a)            #поэлементное деление массивов
print(b**a)             #поэлементно возведение в степень массива b элементами массива a
print(np.dot(a, b))     #матричное произведение массивов

[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[  5.   4. 216.]
27.0


In [4]:
x = np.linspace(0, 9, 10)
print(x)
y = np.sin(x)     #нахождение синусов всех элементов массива
print(y)
print(type(y))     
y2 = np.sqrt(x)
print(y2)         #нахождение кв. кореней всех элементов массива

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
<class 'numpy.ndarray'>
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
