In [ ]:
import numpy as np

In [9]:
#создание одномерного масива a1 = [0 1 2 3 4] из списка my_list
my_list = [0, 1, 2, 3, 4]
a1 = np.array(my_list)
print(a1)
print(type(a1))


[0 1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
#создание двумерного масива a1 = [[1. 2. 3.] [4. 5. 6.]] типа даных float
a2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(a2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
#создание масивов с помощью функции numpy.arange(start, stop, step) типа даных float
a3 = np.arange(5, dtype=float)
a4 = np.arange(11, 16, 2, dtype=float)
print(a3)
print(a4)

[0. 1. 2. 3. 4.]
[11. 13. 15.]


In [12]:
#создание масива с помощью функции numpy.arange(start, stop, step) типа даных float
a5 = np.linspace(0, 1, 6, dtype=float) #интервал диопазона равен (1-0)/5 = 0,2
print(a5)

[0.  0.2 0.4 0.6 0.8 1. ]


In [13]:
#создание масива из нулей numpy.zeros(n) типа даных int
a6 = np.zeros(7, dtype=int)
print(a6)

[0 0 0 0 0 0 0]


In [14]:
#создание масива из единиц numpy.ones(n) типа даных int
a7 = np.ones(3, dtype=int)
print(a7)

[1 1 1]
